# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(768, 670)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"    color: #000;\n"
"}\n"
"\n"
"#head{\n"
"    background-color: #f7f7fc;\n"
"}\n"
"\n"
"#leftMenu{\n"
"    background-color: #eeeeff;\n"
"}\n"
"\n"
"#leftHeaderFrame{\n"
"    background-color: #f7f7fc;\n"
"}\n"
"\n"
"#centralwidget{\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"#mainBody{\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#reportButton{\n"
"    background-color: #7f7fd7;\n"
"    padding: 5px;\n"
"    text-align: left;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#conditionButton{\n"
"    color: #000;\n"
"    padding: 5px;\n"
"    text-align: left;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#messageButton{\n"
"    color: #000;\n"
"    padding: 5px;\n"
"    text-align: left;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#reportButton{\n"
"    color: #000;\n"
"    padding: 5px;\n"
"    text-align: left;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#logoButton{\n"
"    color: #000;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.container = QtWidgets.QWidget(self.centralwidget)
        self.container.setObjectName("container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.container)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.head = QtWidgets.QWidget(self.container)
        self.head.setObjectName("head")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.head)
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logoButton = QtWidgets.QPushButton(self.head)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoButton.sizePolicy().hasHeightForWidth())
        self.logoButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Mulish")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.logoButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/roadIcons/assets/icons/traffic-light-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoButton.setIcon(icon)
        self.logoButton.setIconSize(QtCore.QSize(32, 32))
        self.logoButton.setCheckable(False)
        self.logoButton.setObjectName("logoButton")
        self.horizontalLayout_3.addWidget(self.logoButton)
        self.verticalLayout.addWidget(self.head)
        self.body = QtWidgets.QWidget(self.container)
        self.body.setObjectName("body")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.body)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftMenu = QtWidgets.QWidget(self.body)
        self.leftMenu.setObjectName("leftMenu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.leftMenu)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.menuFrame = QtWidgets.QFrame(self.leftMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuFrame.sizePolicy().hasHeightForWidth())
        self.menuFrame.setSizePolicy(sizePolicy)
        self.menuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuFrame.setObjectName("menuFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.menuFrame)
        self.verticalLayout_6.setContentsMargins(15, 10, 10, 10)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(self.menuFrame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(22)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.reportButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reportButton.sizePolicy().hasHeightForWidth())
        self.reportButton.setSizePolicy(sizePolicy)
        self.reportButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Mulish")
        font.setPointSize(10)
        self.reportButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/roadIcons/assets/icons/chart-column-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reportButton.setIcon(icon1)
        self.reportButton.setIconSize(QtCore.QSize(32, 32))
        self.reportButton.setObjectName("reportButton")
        self.verticalLayout_7.addWidget(self.reportButton)
        self.conditionButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conditionButton.sizePolicy().hasHeightForWidth())
        self.conditionButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Mulish")
        font.setPointSize(10)
        self.conditionButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/roadIcons/assets/icons/triangle-exclamation-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.conditionButton.setIcon(icon2)
        self.conditionButton.setIconSize(QtCore.QSize(32, 32))
        self.conditionButton.setObjectName("conditionButton")
        self.verticalLayout_7.addWidget(self.conditionButton)
        self.messageButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messageButton.sizePolicy().hasHeightForWidth())
        self.messageButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Mulish")
        font.setPointSize(10)
        self.messageButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/roadIcons/assets/icons/envelope-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.messageButton.setIcon(icon3)
        self.messageButton.setIconSize(QtCore.QSize(32, 32))
        self.messageButton.setObjectName("messageButton")
        self.verticalLayout_7.addWidget(self.messageButton)
        self.verticalLayout_6.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_5.addWidget(self.menuFrame)
        self.horizontalLayout_2.addWidget(self.leftMenu)
        self.mianBody = QtWidgets.QWidget(self.body)
        self.mianBody.setObjectName("mianBody")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mianBody)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchFrmae = QtWidgets.QWidget(self.mianBody)
        self.searchFrmae.setObjectName("searchFrmae")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.searchFrmae)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.searchFrmae)
        font = QtGui.QFont()
        font.setFamily("Mulish")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignBottom)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(15, 10, 15, 10)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(30)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.searchFrmae)
        font = QtGui.QFont()
        font.setFamily("Mulish")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.searchFrmae)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.searchFrmae)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.searchFrmae)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_4 = QtWidgets.QLabel(self.searchFrmae)
        font = QtGui.QFont()
        font.setFamily("Mulish")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.searchFrmae)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.verticalLayout_2.addWidget(self.searchFrmae, 0, QtCore.Qt.AlignTop)
        self.resultsFrame = QtWidgets.QWidget(self.mianBody)
        self.resultsFrame.setObjectName("resultsFrame")
        self.verticalLayout_2.addWidget(self.resultsFrame)
        self.horizontalLayout_2.addWidget(self.mianBody)
        self.verticalLayout.addWidget(self.body)
        self.horizontalLayout.addWidget(self.container)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Traffico"))
        self.logoButton.setText(_translate("MainWindow", "Traffico"))
        self.reportButton.setText(_translate("MainWindow", "Road Maintainance"))
        self.conditionButton.setText(_translate("MainWindow", "Road Conditions"))
        self.messageButton.setText(_translate("MainWindow", "Messages"))
        self.label.setText(_translate("MainWindow", "Search Options"))
        self.label_2.setText(_translate("MainWindow", "Location"))
        self.label_3.setText(_translate("MainWindow", "Start Date and time"))
        self.label_4.setText(_translate("MainWindow", "End Date and time"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
